server=1
rpcuser=test
rpcpassword=test
rpcport=18304
port=18305
rpcallowip=0.0.0.0/0
regtest=1
daemon=1
addnode=127.0.0.1:18301
addnode=127.0.0.1:18303

# default = "~/ZoKrates"
zokrateshome="/root/ZoKrates"