#!/bin/bash

if [ $# != 2 ]; then
    echo "usage: ourcontract-mkdll [CONTRACTS DIR] [CONTRACT]"
else
    if [ -f "$1/$2/code.so" ]; then
        echo "The shared object file already exists. Skipping compilation."
    else
        g++ -fPIC -g -c -Wall -o "$1/$2/code.o" "$1/$2/code.cpp"
        g++ -shared -Wl,-soname,"$2/code.so" -o "$1/$2/code.so" "$1/$2/code.o" -lssl -lcrypto
        rm -f "$1/$2/code.o"
    fi
fi
