#!/bin/bash
set -e

if [ $# -ne 2 ]; then
    echo "usage: ourcontract-mkdll [CONTRACTS DIR] [CONTRACT]"
    exit 1
fi

CONTRACT_DIR="$1/$2"
CODE_CPP="$CONTRACT_DIR/code.cpp"
CODE_O="$CONTRACT_DIR/code.o"
CODE_SO="$CONTRACT_DIR/code.so"

if [ -f "$CODE_SO" ]; then
    echo "The shared object file already exists. Skipping compilation."
else
    # Compile contract source
    g++ -fPIC -g -Wall -c -o "$CODE_O" "$CODE_CPP"

    # Link shared object
    g++ -shared -Wl,-soname,"code.so" \
        -o "$CODE_SO" "$CODE_O" \
        -lssl -lcrypto

    # Clean up
    rm -f "$CODE_O"
fi